version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - db
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=clima
            - DB_USERNAME=user_clima
            - DB_PASSWORD=clima
        ports:
            - "9000:9000"

    db:
        image: postgres:15
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: clima
            POSTGRES_USER: user_clima
            POSTGRES_PASSWORD: clima
        ports:
            - "5432:5432"
        networks:
            - laravel_network
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network:

volumes:
    db_data:
